const entityIcons = {
  DRONE: "drone",
  MISSION: "mission",
  INCIDENT: "incident",
  REPORT: "report",
  DOCUMENT: "success"
};

export const formatRelativeTime = (timestamp) => {
  const date = new Date(timestamp);
  const diffMinutes = Math.max(0, Math.floor((Date.now() - date.getTime()) / 60000));

  if (diffMinutes < 1) return "Just now";
  if (diffMinutes < 60) return `${diffMinutes} min ago`;

  const diffHours = Math.floor(diffMinutes / 60);
  if (diffHours < 24) return `${diffHours} hr${diffHours === 1 ? "" : "s"} ago`;

  const diffDays = Math.floor(diffHours / 24);
  if (diffDays < 7) return `${diffDays} day${diffDays === 1 ? "" : "s"} ago`;

  return date.toLocaleDateString();
};

export const buildRecentActivityFromAudit = (auditLogs = [], limit = 6) => {
  return auditLogs
    .map(toAuditEvent)
    .filter(Boolean)
    .slice(0, limit)
    .map((item) => ({
      ...item,
      time: formatRelativeTime(item.timestamp)
    }));
};

export const buildNotificationsFromEvents = ({ auditLogs = [], telemetryRows = [] }, limit = 8) => {
  const auditItems = auditLogs.map(toAuditNotification).filter(Boolean);
  const telemetryItems = buildTelemetryNotifications(telemetryRows);

  return [...auditItems, ...telemetryItems]
    .filter((item) => item.timestamp)
    .sort((left, right) => new Date(right.timestamp) - new Date(left.timestamp))
    .slice(0, limit)
    .map((item) => ({
      ...item,
      time: formatRelativeTime(item.timestamp)
    }));
};

const toAuditEvent = (log) => {
  const descriptor = describeAudit(log);
  if (!descriptor) return null;

  return {
    id: `audit-${log.id}`,
    label: descriptor.label,
    timestamp: log.createdAt,
    type: descriptor.type
  };
};

const toAuditNotification = (log) => {
  const descriptor = describeAudit(log);
  if (!descriptor) return null;

  return {
    id: `audit-${log.id}`,
    title: descriptor.title,
    message: descriptor.message,
    priority: descriptor.priority,
    timestamp: log.createdAt,
    targetPath: getNotificationTargetPath(log)
  };
};

const describeAudit = (log) => {
  const actorName = log.actor?.name ?? "A team member";
  const entityLabel = getEntityLabel(log);
  const type = entityIcons[log.entityType] ?? "success";

  switch (log.action) {
    case "DRONE_CREATED":
      return createDescriptor(type, "info", `${actorName} registered ${entityLabel}`, "Drone registered", `${entityLabel} was added to the fleet by ${actorName}.`);
    case "DRONE_UPDATED":
      return createDescriptor(type, "info", `${actorName} updated ${entityLabel}`, "Drone updated", `${entityLabel} was updated by ${actorName}.`);
    case "DRONE_DELETED":
      return createDescriptor(type, "warning", `${actorName} removed ${entityLabel}`, "Drone removed", `${entityLabel} was removed from the fleet by ${actorName}.`);
    case "MISSION_CREATED":
      return createDescriptor(type, "info", `${actorName} created mission ${entityLabel}`, "Mission created", `${entityLabel} was created by ${actorName}.`);
    case "MISSION_SUBMITTED_FOR_APPROVAL":
      return createDescriptor(type, "warning", `${actorName} submitted mission ${entityLabel} for approval`, "Mission awaiting approval", `${entityLabel} is waiting for system administrator approval.`);
    case "MISSION_APPROVED":
      return createDescriptor(type, "info", `${actorName} approved mission ${entityLabel}`, "Mission approved", `${entityLabel} has been approved and can now move forward.`);
    case "MISSION_UPDATED":
      return createDescriptor(type, "info", `${actorName} updated mission ${entityLabel}`, "Mission updated", `${entityLabel} was updated by ${actorName}.`);
    case "MISSION_STARTED":
      return createDescriptor(type, "warning", `${actorName} started mission ${entityLabel}`, "Mission started", `${entityLabel} is now active.`);
    case "MISSION_COMPLETED":
      return createDescriptor(type, "info", `${actorName} completed mission ${entityLabel}`, "Mission completed", `${entityLabel} was completed by ${actorName}.`);
    case "INCIDENT_CREATED":
      return createDescriptor(type, severityPriority(log.metadata?.severity), `${actorName} logged incident ${entityLabel}`, "Incident logged", `${entityLabel} was logged by ${actorName}.`);
    case "INCIDENT_UPDATED":
      return createDescriptor(type, severityPriority(log.metadata?.severity), `${actorName} updated incident ${entityLabel}`, "Incident updated", `${entityLabel} was updated by ${actorName}.`);
    case "INCIDENT_DELETED":
      return createDescriptor(type, "warning", `${actorName} removed incident ${entityLabel}`, "Incident removed", `${entityLabel} was removed by ${actorName}.`);
    case "REPORT_CREATED":
    case "REPORT_GENERATED":
      return createDescriptor(type, "info", `${actorName} generated ${entityLabel}`, "Report generated", `${entityLabel} was generated by ${actorName}.`);
    case "REPORT_DELETED":
      return createDescriptor(type, "warning", `${actorName} deleted ${entityLabel}`, "Report deleted", `${entityLabel} was deleted by ${actorName}.`);
    case "DOCUMENT_CREATED":
      return createDescriptor(type, "info", `${actorName} created ${entityLabel}`, "Document created", `${entityLabel} metadata was added by ${actorName}.`);
    case "DOCUMENT_UPLOADED":
      return createDescriptor(type, "info", `${actorName} uploaded ${entityLabel}`, "Document uploaded", `${entityLabel} was uploaded by ${actorName}.`);
    case "USER_REGISTERED":
      return createDescriptor("success", "info", `${actorName} created a new account`, "User registered", `${actorName} created a new DroneOps account.`);
    case "USER_REGISTERED_GOOGLE":
      return createDescriptor("success", "info", `${actorName} joined with Google`, "Google sign-in account created", `${actorName} completed Google-based account setup.`);
    case "USER_VERIFIED":
      return createDescriptor("success", "info", `${actorName} verified their account`, "User verified", `${actorName} verified their email and activated access.`);
    case "PASSWORD_RESET":
      return createDescriptor("success", "warning", `${actorName} reset account access`, "Password reset", `${actorName} completed a password reset.`);
    default:
      return createDescriptor(type, "info", `${actorName} recorded ${formatAction(log.action)}`, "System activity", `${actorName} recorded ${formatAction(log.action)}.`);
  }
};

const createDescriptor = (type, priority, label, title, message) => ({
  type,
  priority,
  label,
  title,
  message
});

const getEntityLabel = (log) => {
  const metadata = log.metadata ?? {};

  if (log.entityType === "DRONE") {
    return metadata.droneCode ?? metadata.model ?? "drone";
  }

  if (log.entityType === "MISSION") {
    return metadata.missionCode ?? metadata.name ?? "mission";
  }

  if (log.entityType === "INCIDENT") {
    return metadata.incidentCode ?? metadata.title ?? "incident";
  }

  if (log.entityType === "REPORT") {
    return metadata.title ?? metadata.type?.toString().toLowerCase().replaceAll("_", " ") ?? "report";
  }

  if (log.entityType === "DOCUMENT") {
    return metadata.title ?? metadata.linkedEntityType?.toString().toLowerCase() ?? "document";
  }

  return log.entityType?.toString().toLowerCase() ?? "record";
};

const severityPriority = (severity) => {
  return ["HIGH", "CRITICAL"].includes(String(severity ?? "").toUpperCase()) ? "critical" : "warning";
};

const formatAction = (action = "") => action.toString().toLowerCase().replaceAll("_", " ");

const getNotificationTargetPath = (log) => {
  const entityId = log.entityId ? encodeURIComponent(log.entityId) : "";
  const isDeleted = log.action?.toString().endsWith("_DELETED");

  switch (log.entityType) {
    case "DRONE":
      return isDeleted || !entityId ? "/fleet" : `/fleet/${entityId}`;
    case "MISSION":
      return isDeleted || !entityId ? "/missions" : `/missions/${entityId}`;
    case "INCIDENT":
      return isDeleted || !entityId ? "/incidents" : `/incidents/${entityId}`;
    case "REPORT":
      return isDeleted || !entityId ? "/reports" : `/reports/${entityId}`;
    case "USER":
      return "/users";
    case "DOCUMENT":
      return "/reports";
    default:
      return "/dashboard";
  }
};

const buildTelemetryNotifications = (telemetryRows = []) => {
  return telemetryRows.flatMap((row) => {
    const telemetry = row.telemetry ?? row;
    const droneLabel = row.drone?.droneCode ?? telemetry.droneId ?? "Drone";
    const droneId = row.drone?.id ?? telemetry.droneId;
    const targetPath = droneId ? `/fleet/${encodeURIComponent(droneId)}` : "/fleet";
    const alerts = [];

    if (Number(telemetry.battery?.level ?? telemetry.batteryLevel) < 20) {
      alerts.push({
        id: `battery-${row.drone?.id ?? telemetry.droneId ?? droneLabel}`,
        title: "Low battery",
        message: `${droneLabel} battery is at ${telemetry.battery?.level ?? telemetry.batteryLevel}%.`,
        priority: "critical",
        timestamp: telemetry.timestamp,
        targetPath
      });
    }

    if (Number(telemetry.signal?.strength ?? telemetry.signalStrength) < 45) {
      alerts.push({
        id: `signal-${row.drone?.id ?? telemetry.droneId ?? droneLabel}`,
        title: "Weak signal",
        message: `${droneLabel} signal strength is ${telemetry.signal?.strength ?? telemetry.signalStrength}%.`,
        priority: "warning",
        timestamp: telemetry.timestamp,
        targetPath
      });
    }

    return alerts;
  });
};
